### PR TITLE
Replace all direct shell calls to git with isomorphic-git

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #89

### CODE REVIEW

**Comment by mrjones2014** [comment]
@hsheikhali1 could use some help testing this if you have time. Make sure to test all commands/options.

**Comment by hsheikhali1** [comment]
@mrjones2014 Hey man finally got some time to work on yactl :)

**Review by hsheikhali1 — APPROVED** [review]
I tested this pretty thoroughly and it works as intended - in `last-commit-message-middleware.ts` I was kinda confused why you were setting index to `undefined` your comment says to make it undefined to pass it cleverly to substring(start, end)

**Comment by mrjones2014** [comment]
Yeah if `index` is `undefined`, it goes all the way to the end of the string.

**Pull request merged**
