### PR TITLE
Allowed config files to be hidden files

### PR DESCRIPTION
**Pull request by vishal-codes**
Resolves: #164 

## How to Test
1. `yarn build`
2. Rename the config file to each of the new names added to the array of supported filenames
3. Run `./dist/index.js validate --verbose` and check that the config file is found in the output

## Potential Side Effects/Things to Look Out For
No potential side effects

### CODE REVIEW

**Comment by mrjones2014** [comment]
Hi @vishal-codes reviewing the code is not the same as testing. Please provide instructions for actually testing the code changes under the “how to test” section.

**Comment by vishal-codes** [comment]
> Hi @vishal-codes reviewing the code is not the same as testing. Please provide instructions for actually testing the code changes under the “how to test” section.

I m not getting, how can we test the above feature?

**Comment by mrjones2014** [comment]
@vishal-codes you could run `yarn build`, then rename the config file for this project to each of the supported config file names, and for each file name, run `./dist/index.js validate --verbose` and ensure the output says it's using the correct config file.

**Comment by vishal-codes** [comment]
> @vishal-codes you could run `yarn build`, then rename the config file for this project to each of the supported config file names, and for each file name, run `./dist/index.js validate --verbose` and ensure the output says it's using the correct config file.

I didn't get this and I am still new to the tests thing I guess I should close this pr as I m not confident that I can accomplish this

**Comment by vishal-codes** [comment]
> @vishal-codes you could run `yarn build`, then rename the config file for this project to each of the supported config file names, and for each file name, run `./dist/index.js validate --verbose` and ensure the output says it's using the correct config file.

I didn't get this and I am still new to the tests thing I guess I should close this pr as I m not confident that I can accomplish this

**Comment by mrjones2014** [comment]
Hey @vishal-codes there was no reason to close this PR -- the code looks good, it just needed testing instructions. Since you chose to close the PR, I guess I can re-open it and handle it myself.

**Comment by mrjones2014** [comment]
Tested locally. Works as expected.

**Review by mrjones2014 — APPROVED** [review]

**Pull request merged**
