### PR TITLE
Updated PR template to make sure people are reading the contributing …

### PR DESCRIPTION
**Pull request by vishal-codes**
Resolves: #137 

## How to Test
Check out the `pull_request_template.md` file

## Potential Side Effects/Things to Look Out For
No side effects

### CODE REVIEW

**Comment by mrjones2014** [comment]
Hey @vishal-codes, you'll need to add a changelog entry as well. Please read [CONTRIBUTING.md](https://github.com/mrjones2014/yaclt/blob/master/CONTRIBUTING.md) 😆

**Comment by mrjones2014** [comment]
@vishal-codes you didn't need to close the PR, you could have just added the changelog to this PR 😄

**Comment by vishal-codes** [comment]
> @vishal-codes you didn't need to close the PR, you could have just added the changelog to this PR smile

ahh!!! I m sorry :( but I deleted the branch, also now I m half done for new PR. Please can I go with new PR.

**Comment by mrjones2014** [comment]
yes that's fine.

**Pull request closed without merging**
